package com.softellix.alucalc.utils

import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.setValue

object LanguageManager {
    var currentLanguage by mutableStateOf("GUJARATI")

    fun setLanguage(lang: String) {
        currentLanguage = lang.uppercase()
    }

    fun tr(key: String): String {
        return when (currentLanguage) {
            "HINDI" -> hindiStrings[key] ?: englishStrings[key] ?: key
            "GUJARATI" -> gujaratiStrings[key] ?: englishStrings[key] ?: key
            else -> englishStrings[key] ?: key
        }
    }

    private val englishStrings = mapOf(
        "home" to "Home",
        "projects" to "Projects",
        "reports" to "Reports",
        "settings" to "Settings",
        "all_projects" to "Projects",

        "welcome_back" to "Welcome Back",
        "welcome_back_user" to "Welcome back,",
        "create_account" to "Create Account",
        "login" to "Login",
        "register" to "Register",
        "personal_info" to "PERSONAL INFO",
        "phone_number" to "PHONE NUMBER",
        "password" to "PASSWORD / PIN",
        "new_password" to "NEW PASSWORD",
        "confirm_password" to "CONFIRM PASSWORD",
        "reg_sub" to "Register Barimap to start estimations.",
        "login_sub" to "Login to continue your window estimations.",
        "demo_fill" to "⚡ Tap to Fill Test Credentials",
        "enter_name" to "Enter full name",
        "enter_biz" to "Enter business name",
        "enter_phone" to "Enter 10-digit number",
        "pin_placeholder" to "must be 4 digit only",
        "forgot_password" to "Forgot Password?",
        "remember_password" to "Remembered your password?",
        "back_to_login" to "Back to Login",
        "no_account" to "Don't have an account?",
        "have_account" to "Already have an account?",
        "guest_demo" to "Bypass Login (Guest Demo)",
        "reset_password" to "Reset Your Password",
        "reset_sub" to "Enter your registered phone number to receive OTP.",
        "send_otp" to "Send OTP",
        "enter_otp" to "Enter OTP",
        "verify_otp" to "Verify OTP",

        "new_project" to "New Estimation Project",
        "calculate_sub" to "Calculate dimensions, profiles, and tracks",
        "recent_projects" to "Recent Projects",
        "report_history" to "Report History",

        "step_1_sub" to "STEP 1 OF 3",
        "step_2_sub" to "STEP 2 OF 3",
        "step_3_sub" to "STEP 3 OF 3",
        "pct_33" to "33% Complete",
        "pct_67" to "67% Complete",
        "pct_100" to "100% Complete",

        "project_details" to "PROJECT DETAILS",
        "project_name" to "Project Name",
        "contact_info" to "Contact Information",
        "street_address" to "Street Address",
        "next" to "Next",
        "creating_project" to "Creating Project...",

        "select_profile" to "Select Profile",
        "choose_profile" to "Choose Profile Type",
        "choose_profile_sub" to "Choose a profile type for your window.",
        "regular_series" to "REGULAR SERIES",
        "slim_series" to "SLIM SERIES",
        "reg_40mm" to "Regular 40mm",
        "reg_60mm" to "Regular 60mm",
        "slim_65mm" to "Slim 65mm",

        "add_windows" to "Add Windows",
        "units_info" to "💡 Window Units: Inches & Doro (1 Inch = 8 Doro)",
        "height" to "HEIGHT",
        "width" to "WIDTH",
        "inches" to "Inches",
        "doro" to "Doro (0-7)",
        "quantity" to "Quantity",
        "track_type" to "Track Type",
        "two_track" to "2 Track",
        "three_track" to "3 Track",
        "four_track" to "4 Track",
        "added_windows" to "ADDED WINDOWS",
        "no_windows_added" to "No windows added yet. Enter Inches & Doro above and tap 'Add Another Window'.",
        "add_another_window" to "Add Another Window",
        "save_calculate" to "Save & Calculate",
        "back_to_home" to "Back to Home",

        "report" to "Report",
        "calc_breakdown" to "DETAILED CALCULATION BREAKDOWN",
        "estimator" to "ESTIMATOR",
        "created_date" to "CREATED DATE",
        "total_windows" to "TOTAL WINDOWS",
        "download_pdf" to "Download PDF Report",
        "share_report" to "Share Complete Report",

        "sec_interlock_handle" to "1. Interlock & Handle",
        "sec_top_side" to "2. Top & Side",
        "sec_top_bottom" to "3. Top & Bottom",
        "sec_glass_dimensions" to "4. Glass Dimensions (Width & Height)",
        "window_prefix" to "Window",
        "track_unit" to "Track",
        "qty_unit" to "Qty",
        "pcs_unit" to "pcs",
        "handle_short" to "H",
        "interlock_short" to "I",
        "disclaimer_text" to "Calculations generated using Aluminum Standard Multipliers. Track cuts and glass sizing reflect total pieces.",

        "delete_report_title" to "Delete Report?",
        "delete_report_confirm" to "Are you sure you want to delete this estimation report?",
        "delete" to "Delete",
        "cancel" to "Cancel",
        "deleted_success" to "Report deleted successfully",

        "help_support_title" to "HELP & SUPPORT",
        "customer_care" to "Customer Care",
        "call_action" to "Call",
        "whatsapp_support" to "WhatsApp Support",
        "chat_action" to "Chat",

        "projects_title" to "Projects",
        "manage_projects_sub" to "Manage and view all your estimation projects",
        "search_placeholder" to "Search projects by name or address...",
        "all_projects_count" to "ALL PROJECTS",
        "no_projects_yet" to "No projects created yet. Tap '+' below to create your first project!",
        "no_projects_match" to "No projects matching search",

        "reports_title" to "Report History",
        "manage_reports_sub" to "Access and share all previously generated calculation reports",
        "generated_reports_count" to "GENERATED REPORTS",
        "no_reports_yet" to "No estimation reports generated yet.",
        "aluminum" to "Aluminum",
        "glass_area" to "Glass Area",
        "created_on" to "Created on",

        "settings_title" to "Settings & Profile",
        "manage_settings_sub" to "Manage user preferences and account settings",
        "preferences" to "PREFERENCES",
        "app_language" to "Application Language",
        "logout" to "Logout",
        "logged_out" to "Logged out successfully"
    )

    private val hindiStrings = mapOf(
        "home" to "होम",
        "projects" to "प्रोजेक्ट्स",
        "reports" to "रिपोर्ट",
        "settings" to "સેટિંગ્સ",
        "all_projects" to "प्रोजेक्ट्स",

        "welcome_back" to "आपका स्वागत है",
        "welcome_back_user" to "आपका स्वागत है,",
        "create_account" to "खाता बनाएं",
        "login" to "लॉगिन करें",
        "register" to "रजिस्टर करें",
        "personal_info" to "व्यक्तिगत जानकारी",
        "phone_number" to "फोन नंबर",
        "password" to "पासवर्ड / पिन",
        "new_password" to "नया पासवर्ड",
        "confirm_password" to "पासवर्ड की पुष्टि करें",
        "reg_sub" to "अनुमान शुरू करने के लिए બારીમાપ पर रजिस्टर करें।",
        "login_sub" to "अपनी खिड़की के अनुमानों को जारी रखने के लिए लॉगिन करें।",
        "demo_fill" to "⚡ टेस्ट डेटा भरने के लिए टैप करें",
        "enter_name" to "पूरा नाम दर्ज करें",
        "enter_biz" to "व्यवसाय का नाम दर्ज करें",
        "enter_phone" to "10-अंकों का नंबर दर्ज करें",
        "pin_placeholder" to "केवल 4 अंकों का पिन लिखें",
        "forgot_password" to "पासवर्ड भूल गए?",
        "remember_password" to "अपना पासवर्ड याद आया?",
        "back_to_login" to "लॉगिन पर वापस जाएं",
        "no_account" to "खाता नहीं है?",
        "have_account" to "पहले से खाता है?",
        "guest_demo" to "गेस्ट डेमो (सीधा प्रवेश)",
        "reset_password" to "अपना पासवर्ड रीसेट करें",
        "reset_sub" to "ओटीपी प्राप्त करने के लिए अपना पंजीकृत फोन नंबर दर्ज करें।",
        "send_otp" to "ओटीपी भेजें",
        "enter_otp" to "ओटीपी दर्ज करें",
        "verify_otp" to "ओटीपी सत्यापित करें",

        "new_project" to "नया अनुमान प्रोजेक्ट",
        "calculate_sub" to "आयाम, प्रोफ़ाइल और ट्रैक की गणना करें",
        "recent_projects" to "हाल के प्रोजेक्ट",
        "report_history" to "रिपोर्ट इतिहास",

        "step_1_sub" to "चरण 1 / 3",
        "step_2_sub" to "चरण 2 / 3",
        "step_3_sub" to "चरण 3 / 3",
        "pct_33" to "33% पूर्ण",
        "pct_67" to "67% पूर्ण",
        "pct_100" to "100% पूर्ण",

        "project_details" to "प्रोजेक्ट विवरण",
        "project_name" to "प्रोजेक्ट का नाम",
        "contact_info" to "संपर्क जानकारी",
        "street_address" to "पता (Street Address)",
        "next" to "आगे बढ़ें",
        "creating_project" to "प्रोजेक्ट बना रहे हैं...",

        "select_profile" to "प्रोफ़ाइल चुनें",
        "choose_profile" to "प्रोफ़ाइल प्रकार चुनें",
        "choose_profile_sub" to "अपनी खिड़की के लिए प्रोफ़ाइल प्रकार चुनें।",
        "regular_series" to "रेगुलर सीरीज",
        "slim_series" to "स्लिम सीरीज",
        "reg_40mm" to "रेगुलर 40mm",
        "reg_60mm" to "रेगुलर 60mm",
        "slim_65mm" to "स्लिम 65mm",

        "add_windows" to "खिड़कियां जोड़ें",
        "units_info" to "💡 माप की इकाई: इंच और डोरो (1 इंच = 8 डोरो)",
        "height" to "ऊंचाई (Height)",
        "width" to "चौड़ाई (Width)",
        "inches" to "इंच (Inches)",
        "doro" to "डोरो (0-7)",
        "quantity" to "मात्रा (Quantity)",
        "track_type" to "ट्रैक प्रकार (Track Type)",
        "two_track" to "2 ट्रैक",
        "three_track" to "3 ट्रैक",
        "four_track" to "4 ट्रैक",
        "added_windows" to "जोड़ी गई खिड़कियां",
        "no_windows_added" to "अभी तक कोई खिड़की नहीं जोड़ी गई। ऊपर इंच और डोरो दर्ज करें और 'एक और खिड़की जोड़ें' पर टैप करें।",
        "add_another_window" to "एक और खिड़की जोड़ें",
        "save_calculate" to "सहेजें और गणना करें",
        "back_to_home" to "मुख्य पृष्ठ पर जाएं",

        "report" to "रिपोर्ट",
        "calc_breakdown" to "विस्तृत गणना विवरण",
        "estimator" to "अनुमानक (Estimator)",
        "created_date" to "बनाने की तिथि",
        "total_windows" to "कुल खिड़कियां",
        "download_pdf" to "पीडीएफ रिपोर्ट डाउनलोड करें",
        "share_report" to "संपूर्ण रिपोर्ट साझा करें",

        "sec_interlock_handle" to "1. इंटरलॉक और हैंडल",
        "sec_top_side" to "2. टॉप और साइड",
        "sec_top_bottom" to "3. टॉप और बॉटम",
        "sec_glass_dimensions" to "4. कांच का आकार (चौड़ाई और ऊंचाई)",
        "window_prefix" to "विंडो",
        "track_unit" to "ट्रैक",
        "qty_unit" to "मात्रा",
        "pcs_unit" to "नग",
        "handle_short" to "H",
        "interlock_short" to "I",
        "disclaimer_text" to "एल्यूमीनियम मानक गुणकों का उपयोग करके गणना की गई है।",

        "delete_report_title" to "रिपोर्ट डिलीट करें?",
        "delete_report_confirm" to "क्या आप वाकई इस रिपोर्ट को डिलीट करना चाहते हैं?",
        "delete" to "डिलीट करें",
        "cancel" to "रद्द करें",
        "deleted_success" to "रिपोर्ट सफलतापूर्वक डिलीट की गई",

        "help_support_title" to "मदद और सहायता",
        "customer_care" to "कस्टमर केयर",
        "call_action" to "कॉल करें",
        "whatsapp_support" to "व्हाट्सएप सपोर्ट",
        "chat_action" to "चैट करें",

        "projects_title" to "प्रोजेक्ट्स",
        "manage_projects_sub" to "अपने सभी अनुमानित प्रोजेक्ट देखें और प्रबंधित करें",
        "search_placeholder" to "नाम या पते से खोजें...",
        "all_projects_count" to "सभी प्रोजेक्ट",
        "no_projects_yet" to "अभी तक कोई प्रोजेक्ट नहीं बनाया गया। नया प्रोजेक्ट बनाने के लिए नीचे '+' पर टैप करें!",
        "no_projects_match" to "खोज से मेल खाता कोई प्रोजेक्ट नहीं है",

        "reports_title" to "रिपोर्ट इतिहास",
        "manage_reports_sub" to "पहले जनरेट की गई सभी गणना रिपोर्ट देखें और शेयर करें",
        "generated_reports_count" to "जनरेट की गई रिपोर्ट",
        "no_reports_yet" to "अभी तक कोई रिपोर्ट जनरेट नहीं हुई है।",
        "aluminum" to "एल्यूमीनियम",
        "glass_area" to "कांच का क्षेत्रफल",
        "created_on" to "बनाने की तिथि",

        "settings_title" to "સેટિંગ્સ અને પ્રોફાઈલ",
        "manage_settings_sub" to "उपयोगकर्ता प्राथमिकताएं और खाता सेटिंग्स",
        "preferences" to "प्राथमिकताएं",
        "app_language" to "एप्लिकेशन भाषा",
        "logout" to "लॉग आउट करें",
        "logged_out" to "सफलतापूर्वक लॉग आउट हुए"
    )

    private val gujaratiStrings = mapOf(
        "home" to "હોમ",
        "projects" to "પ્રોજેક્ટ્સ",
        "reports" to "રિપોર્ટ",
        "settings" to "સેટિંગ્સ",
        "all_projects" to "પ્રોજેક્ટ્સ",

        "welcome_back" to "તમારું સ્વાગત છે",
        "welcome_back_user" to "તમારું સ્વાગત છે,",
        "create_account" to "ખાતું બનાવો",
        "login" to "લોગિન કરો",
        "register" to "રજીસ્ટર કરો",
        "personal_info" to "અંગત માહિતી",
        "phone_number" to "ફોન નંબર",
        "password" to "પાસવર્ડ / પીન",
        "new_password" to "નવો પાસવર્ડ",
        "confirm_password" to "પાસવર્ડ કન્ફર્મ કરો",
        "reg_sub" to "અંદાજ મેળવવા માટે બારીમાપ પર રજીસ્ટર કરો.",
        "login_sub" to "વિન્ડો અંદાજ ચાલુ રાખવા માટે લોગિન કરો.",
        "demo_fill" to "⚡ ટેસ્ટ ડેટા ભરવા માટે ટેપ કરો",
        "enter_name" to "તમારું પૂરૂં નામ લખો",
        "enter_biz" to "તમારા વ્યવસાયનું નામ લખો",
        "enter_phone" to "૧૦-અંકનો નંબર લખો",
        "pin_placeholder" to "માત્ર ૪-અંકનો પીન/પાસવર્ડ",
        "forgot_password" to "પાસવર્ડ ભૂલી ગયા?",
        "remember_password" to "પાસવર્ડ યાદ છે?",
        "back_to_login" to "લોગિન પર પાછા જાઓ",
        "no_account" to "ખાતું નથી?",
        "have_account" to "પહેલેથી ખાતું છે?",
        "guest_demo" to "ગ્રાહક ડેમો (ડાયરેક્ટ પ્રવેશ)",
        "reset_password" to "તમારો પાસવર્ડ રીસેટ કરો",
        "reset_sub" to "ઓટીપી મેળવવા માટે તમારો રજીસ્ટર્ડ ફોન નંબર લખો.",
        "send_otp" to "ઓટીપી મોકલો",
        "enter_otp" to "ઓટીપી લખો",
        "verify_otp" to "ઓટીપી ચકાસો",

        "new_project" to "નવો અંદાજ પ્રોજેક્ટ",
        "calculate_sub" to "પરિમાણો, પ્રોફાઇલ્સ અને ટ્રેકની ગણતરી કરો",
        "recent_projects" to "તાજેતરના પ્રોજેક્ટ્સ",
        "report_history" to "રિપોર્ટ ઈતિહાસ",

        "step_1_sub" to "પગલું ૧/૩",
        "step_2_sub" to "પગલું ૨/૩",
        "step_3_sub" to "પગલું ૩/૩",
        "pct_33" to "૩૩% પૂર્ણ",
        "pct_67" to "૬૭% પૂર્ણ",
        "pct_100" to "૧૦૦% પૂર્ણ",

        "project_details" to "પ્રોજેક્ટ વિગતો",
        "project_name" to "પ્રોજેક્ટનું નામ",
        "contact_info" to "સંપર્ક માહિતી",
        "street_address" to "સરનામું",
        "next" to "આગળ વધો",
        "creating_project" to "પ્રોજેક્ટ બનાવી રહ્યા છીએ...",

        "select_profile" to "પ્રોફાઇલ પસંદ કરો",
        "choose_profile" to "પ્રોફાઇલનો પ્રકાર પસંદ કરો",
        "choose_profile_sub" to "તમારી વિન્ડો માટે પ્રોફાઇલ પ્રકાર પસંદ કરો.",
        "regular_series" to "રેગ્યુલર સિરીઝ",
        "slim_series" to "સ્લિમ સિરીઝ",
        "reg_40mm" to "રેગ્યુલર ૪૦mm",
        "reg_60mm" to "રેગ્યુલર ૬૦mm",
        "slim_65mm" to "સ્લિમ ૬૫mm",

        "add_windows" to "બારીઓ ઉમેરો",
        "units_info" to "💡 માપન એકમ: ઈંચ અને દોરો (૧ ઈંચ = ૮ દોરા)",
        "height" to "ઊંચાઈ (Height)",
        "width" to "પહોળાઈ (Width)",
        "inches" to "ઈંચ",
        "doro" to "દોરો (0-7)",
        "quantity" to "જથ્થો (Quantity)",
        "track_type" to "ટ્રેકનો પ્રકાર",
        "two_track" to "૨ ટ્રેક",
        "three_track" to "૩ ટ્રેક",
        "four_track" to "૪ ટ્રેક",
        "added_windows" to "ઉમેરેલી બારીઓ",
        "no_windows_added" to "હજુ સુધી કોઈ બારીઓ ઉમેરી નથી. ઉપર ઈંચ અને દોરો લખો અને 'બીજી બારી ઉમેરો' પર ટેપ કરો.",
        "add_another_window" to "બીજી બારી ઉમેરો",
        "save_calculate" to "સાચવો અને ગણતરી કરો",
        "back_to_home" to "હોમ પર પાછા જાઓ",

        "report" to "રિપોર્ટ",
        "calc_breakdown" to "વિગતવાર ગણતરી વિગતો",
        "estimator" to "અંદાજકાર",
        "created_date" to "તારીખ",
        "total_windows" to "કુલ બારીઓ",
        "download_pdf" to "પીડીએફ રિપોર્ટ ડાઉનલોડ કરો",
        "share_report" to "સંપૂર્ણ રિપોર્ટ શેર કરો",

        "sec_interlock_handle" to "૧. ઈન્ટરલોક અને હેન્ડલ",
        "sec_top_side" to "૨. ટોપ અને સાઈડ",
        "sec_top_bottom" to "૩. ટોપ અને બોટમ",
        "sec_glass_dimensions" to "૪. કાચનું માપ (પહોળાઈ અને ઊંચાઈ)",
        "window_prefix" to "વિન્ડો",
        "track_unit" to "ટ્રેક",
        "qty_unit" to "જથ્થો",
        "pcs_unit" to "નંગ",
        "handle_short" to "હે",
        "interlock_short" to "ઈ",
        "disclaimer_text" to "એલ્યુમિનિયમ ગણતરી માપન સિદ્ધાંતો મુજબ કરેલ છે.",

        "delete_report_title" to "રિપોર્ટ ડિલીટ કરો?",
        "delete_report_confirm" to "શું તમે ખરેખર આ અંદાજ રિપોર્ટ ડિલીટ કરવા માંગો છો?",
        "delete" to "ડિલીટ કરો",
        "cancel" to "કેન્સલ",
        "deleted_success" to "રિપોર્ટ સફળતાપૂર્વક ડિલીટ થયો",

        "help_support_title" to "મદદ અને સપોર્ટ",
        "customer_care" to "કસ્ટમર કેર",
        "call_action" to "કોલ કરો",
        "whatsapp_support" to "વોટ્સએપ સપોર્ટ",
        "chat_action" to "ચેટ કરો",

        "projects_title" to "પ્રોજેક્ટ્સ",
        "manage_projects_sub" to "તમારા તમામ અંદાજિત પ્રોજેક્ટ્સ જુઓ અને સંચાલિત કરો",
        "search_placeholder" to "નામ અથવા સરનામા દ્વારા શોધો...",
        "all_projects_count" to "તમામ પ્રોજેક્ટ્સ",
        "no_projects_yet" to "હજુ સુધી કોઈ પ્રોજેક્ટ બનાવ્યા નથી. નવો પ્રોજેક્ટ બનાવવા માટે નીચે '+' પર ટેપ કરો!",
        "no_projects_match" to "શોધ સાથે મેળ ખાતા કોઈ પ્રોજેક્ટ નથી",

        "reports_title" to "રિપોર્ટ ઈતિહાસ",
        "manage_reports_sub" to "અગાઉના તમામ રિપોર્ટ જુઓ અને શેર કરો",
        "generated_reports_count" to "તૈયાર થયેલા રિપોર્ટ",
        "no_reports_yet" to "હજુ સુધી કોઈ રિપોર્ટ તૈયાર થયા નથી.",
        "aluminum" to "એલ્યુમિનિયમ",
        "glass_area" to "કાચનું ક્ષેત્રફળ",
        "created_on" to "બનાવ્યા તારીખ",

        "settings_title" to "સેટિંગ્સ અને પ્રોફાઈલ",
        "manage_settings_sub" to "વાપરનારની પસંદગી અને એકાઉન્ટ સેટિંગ્સ",
        "preferences" to "પસંદગીઓ",
        "app_language" to "એપ્લિકેશન ભાષા",
        "logout" to "લોગ આઉટ કરો",
        "logged_out" to "સફળતાપૂર્વક લોગ આઉટ થયા"
    )
}
